sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t abdalrhman308/ci-cd_test -f Dockerfile.dev .

script:
  - docker run -e CI=true abdalrhman308/ci-cd_test npm run test 