name: Deploy react 
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t abdalrhman308/ci-cd_test -f Dockerfile.dev .
      - run: docker run -e CI=true abdalrhman308/ci-cd_test npm run test
      - run: docker push abdalrhman308/ci-cd_test